# Generated by Django 6.0.1 on 2026-02-01 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("cooked", "Cooked Meal"),
                            ("raw", "Raw Ingredients"),
                            ("packaged", "Packaged Food"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_kg", models.FloatField()),
                ("description", models.TextField()),
                ("expiry_time", models.DateTimeField()),
                ("pickup_instructions", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="listings/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("claimed", "Claimed"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed (Picked Up)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimant_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo taken by claimant at pickup",
                        null=True,
                        upload_to="claims/",
                    ),
                ),
                (
                    "donor_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo taken by donor at handover",
                        null=True,
                        upload_to="claims/",
                    ),
                ),
                (
                    "claimant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
